language: go
sudo: true

go:
  - 1.14.x
  - master

env:
  - GO111MODULE=on GOPROXY=https://goproxy.io,direct

services:
  - rabbitmq
  - elasticsearch

before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.0-amd64.deb -o elasticsearch.deb
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.0-amd64.deb.sha512 -o elasticsearch.deb.sha512
  - shasum -a 512 -c eelasticsearch.deb.sha512
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl restart elasticsearch

addons:
  apt:
    update: true
    packages:
      - rabbitmq-server

install:
  -


before_script:
  - sudo rabbitmqctl add_user test test
  - sudo rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
  # ES 启动速度比较慢
  - sleep 8
  # 对rabbitmq和es做准备工作
  - go run readyfordistributed.go
  ## 编译
  - cd distributed && bash script/build.sh
  ## 运行多个实例
  - bash script/start_min.sh
  - sleep 2

script:
  # 测试部分
  - bash script/test.sh

after_script:
  - bash script/stop_min.sh
  - cd ..

