language: go
sudo: true

go:
  - master

env:
  - GO111MODULE=on GOPROXY=https://goproxy.io,direct

services:
  - rabbitmq
  - elasticsearch

before_install:
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.0-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl restart elasticsearch

addons:
  apt:
    update: true
    packages:
      - rabbitmq-server
  ssh_known_hosts: 119.29.5.95

install:
  -


before_script:
  - sudo rabbitmqctl add_user test test
  - sudo rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
  # ES 启动速度比较慢
  - sleep 8
  # 对rabbitmq和es做准备工作
  - go run readyfordistributed.go
  ## 编译
  - cd distributed && bash script/build.sh
  ## 运行多个实例
  - bash script/start_min.sh
  - sleep 2

script:
  # 测试部分
  - bash script/test.sh
  - cd ..

after_script:
  - cd distributed
  - bash script/stop_min.sh

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  provider: script
  script: bash distributed/script/deploy.sh
  # skip_cleanup: true
  on:
    branch: deploy

